<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\Core\CleenTeeth.Application\CleenTeeth.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\CleanTeeth.Persistence\CleanTeeth.Persistence.csproj" />
  </ItemGroup>

</Project>
